name: Claim Free Games
on:
  schedule:
    - cron: '0 18 * * 4,5' # 每周四和周五 UTC 18:00 运行（对应北京时间周五凌晨）
  workflow_dispatch: # 支持手动触发

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      # --- 插入下面这段 ---
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: always() # 强制运行，方便我们调试
      # ------------------
      - run: node epic-games.js
        env:
          EMAIL: ${{ secrets.EPIC_EMAIL }}
          PASSWORD: ${{ secrets.EPIC_PASSWORD }}
